#!/bin/sh
#
# Time-stamp: <2020-11-05 12:11:45 rene>
#
# Copyright (C) 2010 - 2020 Rene Maurer <rene@cumparsita.ch>
#
# This file is part of rpystart.
#
# rpysrtart is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License Version 2 as
# published by the Free Software Foundation.
#
# rpystart is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PRPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rpystart. If not, see <http://www.gnu.org/licenses/>.
#
# ----------------------------------------------------------------------

flake8 --max-line-length 300 $1
if [ $? = 0 ]; then
    echo "$(basename $1) passed"
fi
