#!/bin/sh
#
# Time-stamp: <2026-02-01 22:58:58 rene>
#
# Copyright (C) 2010 - 2014 Rene Maurer <rene@cumparsita.ch>
#
# This file is part of rpystart.
#
# rpystart is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License Version 2 as
# published by the Free Software Foundation.
#
# rpystart is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PRPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rpystart. If not, see <http://www.gnu.org/licenses/>.
#
# ----------------------------------------------------------------------

clear
echo "We are on $(uname)"
./clean > /dev/null
# find . -name '*.py' -exec ./checkcode-helper '{}' \;
find . -path "*migrations/*" -prune -o -name '*.py' -exec ./checkcode-helper '{}' \;
echo done
