#!/bin/bash
#
# Time-stamp: <2018-09-20 09:16:36 rene>
#
# Copyright (C) 2017 Rene Maurer <rene@cumparsita.ch>.
# Copyright (C) 2017 Albert Alt <saludos@gmx.ch>.
#
# This file is part of tangodjsforgoodsound tdjsfgs.
#
# tangodjsforgoodsound is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# Version 2 as published by the Free Software Foundation.
#
# tangodjsforgoodsound is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PRPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tangodjsforgoodsound. If not, see
# <http://gnu.org/licenses/>.
#
# ----------------------------------------------------------------------

clear

for CHECKER in pyflakes-python2 "pycodestyle2 --ignore W605"; do

    find . -maxdepth 1 -name '*.py' -exec $CHECKER '{}' \;
    for DIR in tangodjsforgoodsound tangodjsforgoodsound/templatetags; do
        find $DIR -maxdepth 1 -name '*.py' -exec $CHECKER '{}' \;
    done
    # echo "$CHECKER DONE"
done

if [ "$1" ]; then
    cloc --quiet --exclude-dir=SAV,test,doc,z .
    echo
else
    echo "cloc disabled, use \$1 to enable."
fi
