# -*- coding: utf-8 -*-
#
# Time-stamp: <2025-10-12 06:54 auto>
#
# Copyright (C) 2025 Rene Maurer <rene@cumparsita.ch>.
#
# This file is part of tangodjsforgoodsound.
#
# tangodjsforgoodsound is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License Version 2 as
# published by the Free Software Foundation.
#
# tangodjsforgoodsound is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PRPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tangodjsforgoodsound. If not, see <http://gnu.org/licenses/>.
#
# ----------------------------------------------------------------------

# Automatically generated by rpyversion.py or the corresponding version
# shell wrapper.

__version__ = "1.6.3"
__date__ = "2025-10-12 06:54"
