"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys
from . import topsecret  # b e  c a r e f u l l !

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = 'loginredirect'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = topsecret._SECRET_KEY

# TODO don't run with debug turned on in production!
DEBUG = os.path.exists("/home/rene")

print("Python Version %s" % (sys.version.split()[0]))
print("mysite.settings.DEBUG=%s" % DEBUG)

# Do not use LongAutoField
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"


ALLOWED_HOSTS = [
    "tangodjsforgoodsound.info",
    "www.tangodjsforgoodsound.info",
    "tdjsfgs.uber.space",
    "localhost", "127.0.0.1",
    "tangodjsforgoodsound.cumparsita.ch"]

CSRF_TRUSTED_ORIGINS = [
    "https://tangodjsforgoodsound.info",
    "https://www.tangodjsforgoodsound.info",
    "https://tdjsfgs.uber.space",
    "https://tangodjsforgoodsound.cumparsita.ch"]

# Application definition
INSTALLED_APPS = [
    'tangodjsforgoodsound.apps.TangodjsforgoodsoundConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tangodjsforgoodsound.context_processors.appData',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Zurich'

Use_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# Note, that correct deployment of static files is TODO
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'tangodjsforgoodsound/static')

# SMTP
EMAIL_USE_TLS = True
EMAIL_HOST = topsecret._EMAIL_HOST
EMAIL_PORT = topsecret._EMAIL_PORT
EMAIL_HOST_USER = topsecret._EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = topsecret._EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = "contact@tangodjsforgoodsound.info"

# Session
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Logging (one tdjsfgs logger for all)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'simple': {
            'format': '%(levelname)s %(asctime)s :: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'simple',
            'filename': os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                     os.pardir, "tdjsfgs.log"),
            'maxBytes': 1024*1024,  # 1 MB
            'backupCount': 2,
        },
    },
    'loggers': {
        'tdjsfgs': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
    },
}
