# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country')),
                ('since', models.IntegerField(choices=[(2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980)], default=2017, verbose_name='Since')),
                ('number_of_milongas', models.IntegerField(null=True, verbose_name='Number of milongas')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Email')),
                ('style', models.CharField(choices=[(b'TRA', 'Traditional'), (b'ALT', 'Alternative'), (b'TA', 'Traditional and alternative')], max_length=100, null=True, verbose_name='Style')),
                ('cortinas', models.CharField(choices=[(b'YES', 'Yes'), (b'NO', 'No')], max_length=10, null=True, verbose_name='Tandas and cortinas')),
                ('audioformat', models.CharField(choices=[(b'', b'-'), (b'AIFF', 'AIFF Audio Interchange File Format (.aiff, aif)'), (b'WAV', 'WAV Resource Interchange File Format (.wav)'), (b'ADA', 'ADA Advanced Digital Audio (.ada)'), (b'ALAC', 'ALAC Apple Lossless Audio Codec (.m4a, .mp4)'), (b'APE', "APE Monkey's Audio (.ape, .mac)"), (b'FLAC', 'FLAC Free Lossless Audio Codec (.flac, .fla)'), (b'SHN', 'SHN Shorten (.shn)'), (b'TTA', 'TTA The True Audio (.tta)'), (b'WV', 'WV WavPack LOSSLESS (.wv)')], default='', max_length=200, verbose_name='Main audio format')),
                ('audioformatmat2', models.CharField(choices=[(b'NONE', 'None'), (b'AIFF', 'AIFF Audio Interchange File Format (.aiff, aif'), (b'WAV', 'WAV Resource Interchange File Format (.wav)'), (b'ADA', 'ADA Advanced Digital Audio (.ada)'), (b'ALAC', 'ALAC Apple Lossless Audio Codec (.m4a, .mp4)'), (b'APE', "APE Monkey's Audio (.ape, .mac)"), (b'FLAC', 'FLAC Free Lossless Audio Codec (.flac, .fla)'), (b'SHN', 'SHN Shorten (.shn)'), (b'TTA', 'TTA The True Audio (.tta)'), (b'WV', 'WV WavPack LOSSLESS (.wv)')], default='NONE', max_length=200, verbose_name='Alternative audio format')),
                ('sources', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sources')),
                ('favorites', models.CharField(blank=True, max_length=200, null=True, verbose_name='Personal favorites, decades')),
                ('computer', models.CharField(choices=[(b'', b'-'), (b'PCW', 'PC Windows'), (b'PCL', 'PC Linux'), (b'MAC', 'MAC'), (b'MOB', 'Mobile device (Tablet, Smartphone, iPhone, iPad, ...)'), (b'OTR', 'Other')], default='', max_length=200, null=True, verbose_name='Computer')),
                ('computermodel', models.CharField(blank=True, max_length=200, null=True, verbose_name='Computer model')),
                ('player', models.CharField(max_length=200, null=True, verbose_name='Player')),
                ('soundcard', models.CharField(max_length=200, null=True, verbose_name='Soundcard')),
                ('soundprocessor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Soundprocessor')),
                ('other_equipment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Other equipment')),
                ('compression', models.CharField(choices=[(b'NEV', 'Never'), (b'SOM', 'Sometimes'), (b'MOS', 'Mostly'), (b'ALW', 'Always')], default='NEV', max_length=100, null=True, verbose_name='Compression')),
                ('equalization', models.CharField(choices=[(b'NEV', 'Never'), (b'SOM', 'Sometimes'), (b'MOS', 'Mostly'), (b'ALW', 'Always')], default='NEV', max_length=100, null=True, verbose_name='Equalization')),
                ('music_remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks')),
                ('backup_computer', models.CharField(choices=[(b'', b'-'), (b'PCW', 'PC Windows'), (b'PCL', 'PC Linux'), (b'MAC', 'MAC'), (b'MOB', 'Mobile device (Tablet, Smartphone, iPhone, iPad, ...)'), (b'OTR', 'Other')], default='', max_length=200, null=True, verbose_name='Computer')),
                ('backup_computermodel', models.CharField(max_length=200, null=True, verbose_name='Computer model')),
                ('backup_player', models.CharField(max_length=200, null=True, verbose_name='Player')),
                ('backup_soundcard', models.CharField(blank=True, max_length=200, null=True, verbose_name='Soundcard')),
                ('backup_soundprocessor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Soundprocessor')),
                ('backup_other_equipment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Other equipment')),
            ],
        ),
    ]
