# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 13:52


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesort', models.CharField(blank=True, default='', max_length=50, verbose_name='Hidden namesort')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='Name')),
                ('gender', models.CharField(blank=True, choices=[(b'MAL', 'Male'), (b'FEM', 'Female')], default='', max_length=100, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(blank=True, default='', max_length=2, verbose_name='Country')),
                ('province', models.CharField(blank=True, default='', max_length=50, verbose_name='Province')),
                ('since', models.IntegerField(blank=True, choices=[(2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980)], default=2017, verbose_name='Since')),
                ('number_of_milongas', models.IntegerField(blank=True, choices=[(0, 0), (10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100), (110, 110), (120, 120), (130, 130), (140, 140), (150, 150), (160, 160), (170, 170), (180, 180), (190, 190), (200, 200), (210, 210), (220, 220), (230, 230), (240, 240), (250, 250), (260, 260), (270, 270), (280, 280), (290, 290), (300, 300), (350, 350), (400, 400), (450, 450), (500, 500), (550, 550), (600, 600), (650, 650), (700, 700), (750, 750), (800, 800), (850, 850), (900, 900), (950, 950), (1000, 1000), (1200, 1200), (1400, 1400), (1600, 1600), (1800, 1800), (2000, 2000)], default=0, verbose_name='Number of milongas')),
                ('email', models.EmailField(blank=True, default='', max_length=300, verbose_name='Email')),
                ('useremail', models.EmailField(blank=True, default='', max_length=300, verbose_name='User Email')),
                ('website', models.URLField(blank=True, default='', max_length=300, verbose_name='Website')),
                ('style', models.CharField(blank=True, choices=[(b'TRA', 'Traditional'), (b'ALT', 'Alternative'), (b'TA', 'Traditional and alternative')], default='', max_length=100, verbose_name='Style')),
                ('cortinas', models.CharField(blank=True, choices=[(b'YES', 'Yes'), (b'NO', 'No')], default='', max_length=100, verbose_name='Tandas and cortinas')),
                ('audioformat', models.CharField(blank=True, choices=[(b'AIFF', 'AIFF Audio Interchange File Format (.aiff, aif)'), (b'WAV', 'WAV Resource Interchange File Format (.wav)'), (b'ADA', 'ADA Advanced Digital Audio (.ada)'), (b'ALAC', 'ALAC Apple Lossless Audio Codec (.m4a, .mp4)'), (b'APE', "APE Monkey's Audio (.ape, .mac)"), (b'FLAC', 'FLAC Free Lossless Audio Codec (.flac, .fla)'), (b'SHN', 'SHN Shorten (.shn)'), (b'TTA', 'TTA The True Audio (.tta)'), (b'WV', 'WV WavPack LOSSLESS (.wv)')], default='', max_length=100, verbose_name='Main audio format')),
                ('audioformat2', models.CharField(blank=True, choices=[(b'AIFF', 'AIFF Audio Interchange File Format (.aiff, aif)'), (b'WAV', 'WAV Resource Interchange File Format (.wav)'), (b'ADA', 'ADA Advanced Digital Audio (.ada)'), (b'ALAC', 'ALAC Apple Lossless Audio Codec (.m4a, .mp4)'), (b'APE', "APE Monkey's Audio (.ape, .mac)"), (b'FLAC', 'FLAC Free Lossless Audio Codec (.flac, .fla)'), (b'SHN', 'SHN Shorten (.shn)'), (b'TTA', 'TTA The True Audio (.tta)'), (b'WV', 'WV WavPack LOSSLESS (.wv)')], default='', max_length=100, verbose_name='Alternative audio format')),
                ('sources', models.CharField(blank=True, default='', max_length=300, verbose_name='Sources')),
                ('favorites', models.CharField(blank=True, default='', max_length=300, verbose_name='Personal favorites, decades')),
                ('music_remark', models.CharField(blank=True, default='', max_length=300, verbose_name='Remarks')),
                ('computer', models.CharField(blank=True, choices=[(b'PCW', 'PC Windows'), (b'PCL', 'PC Linux'), (b'MAC', 'MAC'), (b'MOB', 'Mobile device (Tablet, Smartphone, iPhone, iPad, ...)')], default='', max_length=100, verbose_name='Computer')),
                ('computermodel', models.CharField(blank=True, default='', max_length=300, verbose_name='Computer model')),
                ('player', models.CharField(blank=True, default='', max_length=300, verbose_name='Player')),
                ('audiointerface', models.CharField(blank=True, default='', max_length=300, verbose_name='AudioInterface/DAC')),
                ('soundprocessor', models.CharField(blank=True, default='', max_length=300, verbose_name='Soundprocessor')),
                ('other_equipment', models.CharField(blank=True, default='', max_length=300, verbose_name='Other equipment')),
                ('compression', models.CharField(blank=True, choices=[(b'NEV', 'Never'), (b'SOM', 'Sometimes'), (b'MOS', 'Mostly'), (b'ALW', 'Always')], default='', max_length=100, verbose_name='Compression')),
                ('equalization', models.CharField(blank=True, choices=[(b'NEV', 'Never'), (b'SOM', 'Sometimes'), (b'MOS', 'Mostly'), (b'ALW', 'Always')], default='', max_length=100, verbose_name='Equalization')),
                ('equipment_remark', models.CharField(blank=True, default='', max_length=300, verbose_name='Remarks')),
                ('backup_computer', models.CharField(blank=True, choices=[(b'PCW', 'PC Windows'), (b'PCL', 'PC Linux'), (b'MAC', 'MAC'), (b'MOB', 'Mobile device (Tablet, Smartphone, iPhone, iPad, ...)')], default='', max_length=100, verbose_name='Computer')),
                ('backup_computermodel', models.CharField(blank=True, default='', max_length=300, verbose_name='Computer model')),
                ('backup_player', models.CharField(blank=True, default='', max_length=300, verbose_name='Player')),
                ('backup_audiointerface', models.CharField(blank=True, default='', max_length=300, verbose_name='AudioInterface/DAC')),
                ('backup_soundprocessor', models.CharField(blank=True, default='', max_length=300, verbose_name='Soundprocessor')),
                ('backup_other_equipment', models.CharField(blank=True, default='', max_length=300, verbose_name='Other equipment')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
