# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dj',
            name='backup_soundcard',
        ),
        migrations.RemoveField(
            model_name='dj',
            name='soundcard',
        ),
        migrations.AddField(
            model_name='dj',
            name='audiointerface',
            field=models.CharField(max_length=200, null=True, verbose_name='AudioInterface/DAC'),
        ),
        migrations.AddField(
            model_name='dj',
            name='backup_audiointerface',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AudioInterface/DAC'),
        ),
    ]
