# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0003_auto_20180918_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dj',
            name='backup_soundprocessor',
        ),
        migrations.AddField(
            model_name='dj',
            name='songdisplay',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Song display'),
        ),
        migrations.AddField(
            model_name='dj',
            name='soundprocessor2',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Compressor'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='soundprocessor',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Equalizer'),
        ),
    ]
