# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0003_auto_20170308_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='gender',
            field=models.CharField(choices=[(b'MAL', 'Male'), (b'FEM', 'Female')], default='MAL', max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='audioformat',
            field=models.CharField(choices=[(b'', b''), (b'AIFF', 'AIFF Audio Interchange File Format (.aiff, aif)'), (b'WAV', 'WAV Resource Interchange File Format (.wav)'), (b'ADA', 'ADA Advanced Digital Audio (.ada)'), (b'ALAC', 'ALAC Apple Lossless Audio Codec (.m4a, .mp4)'), (b'APE', "APE Monkey's Audio (.ape, .mac)"), (b'FLAC', 'FLAC Free Lossless Audio Codec (.flac, .fla)'), (b'SHN', 'SHN Shorten (.shn)'), (b'TTA', 'TTA The True Audio (.tta)'), (b'WV', 'WV WavPack LOSSLESS (.wv)')], default='', max_length=80, verbose_name='Main audio format'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='audioformatmat2',
            field=models.CharField(choices=[(b'NONE', 'None'), (b'AIFF', 'AIFF Audio Interchange File Format (.aiff, aif'), (b'WAV', 'WAV Resource Interchange File Format (.wav)'), (b'ADA', 'ADA Advanced Digital Audio (.ada)'), (b'ALAC', 'ALAC Apple Lossless Audio Codec (.m4a, .mp4)'), (b'APE', "APE Monkey's Audio (.ape, .mac)"), (b'FLAC', 'FLAC Free Lossless Audio Codec (.flac, .fla)'), (b'SHN', 'SHN Shorten (.shn)'), (b'TTA', 'TTA The True Audio (.tta)'), (b'WV', 'WV WavPack LOSSLESS (.wv)')], default='NONE', max_length=80, verbose_name='Alternative audio format'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='backup_computer',
            field=models.CharField(choices=[(b'', b''), (b'PCW', 'PC Windows'), (b'PCL', 'PC Linux'), (b'MAC', 'MAC'), (b'MOB', 'Mobile device (Tablet, Smartphone, iPhone, iPad, ...)')], default='', max_length=80, null=True, verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='compression',
            field=models.CharField(choices=[(b'NEV', 'Never'), (b'SOM', 'Sometimes'), (b'MOS', 'Mostly'), (b'ALW', 'Always')], default='NEV', max_length=80, null=True, verbose_name='Compression'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='computer',
            field=models.CharField(choices=[(b'', b''), (b'PCW', 'PC Windows'), (b'PCL', 'PC Linux'), (b'MAC', 'MAC'), (b'MOB', 'Mobile device (Tablet, Smartphone, iPhone, iPad, ...)')], default='', max_length=80, null=True, verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='cortinas',
            field=models.CharField(choices=[(b'YES', 'Yes'), (b'NO', 'No')], max_length=80, null=True, verbose_name='Tandas and cortinas'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='equalization',
            field=models.CharField(choices=[(b'NEV', 'Never'), (b'SOM', 'Sometimes'), (b'MOS', 'Mostly'), (b'ALW', 'Always')], default='NEV', max_length=80, null=True, verbose_name='Equalization'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='style',
            field=models.CharField(choices=[(b'TRA', 'Traditional'), (b'ALT', 'Alternative'), (b'TA', 'Traditional and alternative')], max_length=80, null=True, verbose_name='Style'),
        ),
    ]
