# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0004_auto_20181001_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='last_changed',
            field=models.DateField(auto_now=True, verbose_name='Last changed'),
        ),
    ]
