# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0004_auto_20170309_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dj',
            name='gender',
        ),
    ]
