# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0005_remove_dj_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='gender',
            field=models.CharField(choices=[(b'MAL', 'Male'), (b'FEM', 'Female')], default='MAL', max_length=50, verbose_name='Gender'),
        ),
    ]
