# Generated by Django 4.0.4 on 2022-04-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0008_auto_20220423_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj',
            name='audioformat',
            field=models.CharField(blank=True, choices=[('AIFF', 'AIFF Audio Interchange File Format (.aiff, aif)'), ('FLAC', 'FLAC Free Lossless Audio Codec (.flac, .fla)'), ('WAV', 'WAV Resource Interchange File Format (.wav)'), ('ADA', 'ADA Advanced Digital Audio (.ada)'), ('ALAC', 'ALAC Apple Lossless Audio Codec (.m4a, .mp4)'), ('APE', "APE Monkey's Audio (.ape, .mac)"), ('SHN', 'SHN Shorten (.shn)'), ('TTA', 'TTA The True Audio (.tta)'), ('WV', 'WV WavPack LOSSLESS (.wv)'), ('ANALOG', 'ANALOG Playback of LPs/Shellacs')], default='', max_length=100, verbose_name='Main audio format'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='audioformat2',
            field=models.CharField(blank=True, choices=[('AIFF', 'AIFF Audio Interchange File Format (.aiff, aif)'), ('FLAC', 'FLAC Free Lossless Audio Codec (.flac, .fla)'), ('WAV', 'WAV Resource Interchange File Format (.wav)'), ('ADA', 'ADA Advanced Digital Audio (.ada)'), ('ALAC', 'ALAC Apple Lossless Audio Codec (.m4a, .mp4)'), ('APE', "APE Monkey's Audio (.ape, .mac)"), ('SHN', 'SHN Shorten (.shn)'), ('TTA', 'TTA The True Audio (.tta)'), ('WV', 'WV WavPack LOSSLESS (.wv)'), ('ANALOG', 'ANALOG Playback of LPs/Shellacs')], default='', max_length=100, verbose_name='Alternative audio format'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='backup_computer',
            field=models.CharField(blank=True, choices=[('PCW', 'PC Windows'), ('PCL', 'PC Linux'), ('MAC', 'MAC'), ('MOB', 'Mobile device (Tablet, Smartphone, iPhone, iPad, ...)')], default='', max_length=100, verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='compression',
            field=models.CharField(blank=True, choices=[('NEV', 'Never'), ('SOM', 'Sometimes'), ('MOS', 'Mostly'), ('ALW', 'Always')], default='', max_length=100, verbose_name='Compression'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='computer',
            field=models.CharField(blank=True, choices=[('PCW', 'PC Windows'), ('PCL', 'PC Linux'), ('MAC', 'MAC'), ('MOB', 'Mobile device (Tablet, Smartphone, iPhone, iPad, ...)')], default='', max_length=100, verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='cortinas',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=100, verbose_name='Tandas and cortinas'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='equalization',
            field=models.CharField(blank=True, choices=[('NEV', 'Never'), ('SOM', 'Sometimes'), ('MOS', 'Mostly'), ('ALW', 'Always')], default='', max_length=100, verbose_name='Equalization'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='gender',
            field=models.CharField(blank=True, choices=[('MAL', 'Male'), ('FEM', 'Female')], default='', max_length=100, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='style',
            field=models.CharField(blank=True, choices=[('TRA', 'Traditional'), ('ALT', 'Alternative'), ('TA', 'Traditional and alternative')], default='', max_length=100, verbose_name='Style'),
        ),
    ]
