# Generated by Django 4.2.6 on 2023-10-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0009_alter_dj_audioformat_alter_dj_audioformat2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj',
            name='backup_computer',
            field=models.CharField(blank=True, choices=[('PCW', 'PC Windows'), ('PCL', 'PC Linux'), ('MAC', 'MAC'), ('MOB', 'Mobile device (Tablet, Smartphone, iPhone, iPad, ...)'), ('TTA', 'Turntable(s)')], default='', max_length=100, verbose_name='Computer/Device'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='computer',
            field=models.CharField(blank=True, choices=[('PCW', 'PC Windows'), ('PCL', 'PC Linux'), ('MAC', 'MAC'), ('MOB', 'Mobile device (Tablet, Smartphone, iPhone, iPad, ...)'), ('TTA', 'Turntable(s)')], default='', max_length=100, verbose_name='Computer/Device'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='since',
            field=models.IntegerField(blank=True, choices=[(2023, 2023), (2022, 2022), (2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980)], default=0, verbose_name='Since'),
        ),
    ]
