# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0010_dj_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
