# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 05:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0011_auto_20170908_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj',
            name='audioformat',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'AIFF', 'AIFF Audio Interchange File Format (.aiff, aif)'), (b'WAV', 'WAV Resource Interchange File Format (.wav)'), (b'ADA', 'ADA Advanced Digital Audio (.ada)'), (b'ALAC', 'ALAC Apple Lossless Audio Codec (.m4a, .mp4)'), (b'APE', "APE Monkey's Audio (.ape, .mac)"), (b'FLAC', 'FLAC Free Lossless Audio Codec (.flac, .fla)'), (b'SHN', 'SHN Shorten (.shn)'), (b'TTA', 'TTA The True Audio (.tta)'), (b'WV', 'WV WavPack LOSSLESS (.wv)')], default='', max_length=100, verbose_name='Main audio format'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='audioformatmat2',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'AIFF', 'AIFF Audio Interchange File Format (.aiff, aif)'), (b'WAV', 'WAV Resource Interchange File Format (.wav)'), (b'ADA', 'ADA Advanced Digital Audio (.ada)'), (b'ALAC', 'ALAC Apple Lossless Audio Codec (.m4a, .mp4)'), (b'APE', "APE Monkey's Audio (.ape, .mac)"), (b'FLAC', 'FLAC Free Lossless Audio Codec (.flac, .fla)'), (b'SHN', 'SHN Shorten (.shn)'), (b'TTA', 'TTA The True Audio (.tta)'), (b'WV', 'WV WavPack LOSSLESS (.wv)')], default='', max_length=100, verbose_name='Alternative audio format'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='audiointerface',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='AudioInterface/DAC'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='backup_audiointerface',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='AudioInterface/DAC'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='backup_computer',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'PCW', 'PC Windows'), (b'PCL', 'PC Linux'), (b'MAC', 'MAC'), (b'MOB', 'Mobile device (Tablet, Smartphone, iPhone, iPad, ...)')], default='', max_length=100, verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='backup_computermodel',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Computer model'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='backup_other_equipment',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Other equipment'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='backup_player',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='backup_soundprocessor',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Soundprocessor'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='compression',
            field=models.CharField(blank=True, choices=[(b'NEV', 'Never'), (b'SOM', 'Sometimes'), (b'MOS', 'Mostly'), (b'ALW', 'Always')], default='', max_length=100, verbose_name='Compression'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='computer',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'PCW', 'PC Windows'), (b'PCL', 'PC Linux'), (b'MAC', 'MAC'), (b'MOB', 'Mobile device (Tablet, Smartphone, iPhone, iPad, ...)')], default='', max_length=100, verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='computermodel',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Computer model'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='cortinas',
            field=models.CharField(blank=True, choices=[(b'YES', 'Yes'), (b'NO', 'No')], default='', max_length=100, verbose_name='Tandas and cortinas'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=300, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='equalization',
            field=models.CharField(blank=True, choices=[(b'NEV', 'Never'), (b'SOM', 'Sometimes'), (b'MOS', 'Mostly'), (b'ALW', 'Always')], default='', max_length=100, verbose_name='Equalization'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='favorites',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Personal favorites, decades'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'MAL', 'Male'), (b'FEM', 'Female')], default='', max_length=100, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='music_remarks',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='number_of_milongas',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of milongas'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='other_equipment',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Other equipment'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='player',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='since',
            field=models.IntegerField(blank=True, choices=[(2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980)], default=2017, verbose_name='Since'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='soundprocessor',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Soundprocessor'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='sources',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='style',
            field=models.CharField(blank=True, choices=[(b'TRA', 'Traditional'), (b'ALT', 'Alternative'), (b'TA', 'Traditional and alternative')], default='', max_length=100, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dj',
            name='website',
            field=models.URLField(blank=True, default='', max_length=300, verbose_name='Website'),
        ),
    ]
