# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0013_auto_20170918_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dj',
            old_name='music_remarks',
            new_name='equipment_remark',
        ),
        migrations.AddField(
            model_name='dj',
            name='music_remark',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Remarks'),
        ),
    ]
