# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0014_auto_20170919_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='namesort',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Hidden namesort'),
        ),
    ]
