# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0015_dj_namesort'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='province',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Province'),
        ),
    ]
