# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0016_dj_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dj',
            old_name='audioformatmat2',
            new_name='audioformat2',
        ),
    ]
