# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0017_auto_20171102_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='namesort',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Hidden namesort'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='province',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Province'),
        ),
    ]
