# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangodjsforgoodsound', '0023_auto_20171113_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='useremail',
            field=models.EmailField(blank=True, default='', max_length=300, verbose_name='User Email'),
        ),
    ]
